export default {
    PLATE: require("../assets/images/plate.png"),
    DISCOVER: require("../assets/images/discover.png"),
    DELIVER: require("../assets/images/deliver.png"),
    FAVORITE: require("../assets/images/favorite.png"),
    Google: require("../assets/images/Social/Google.png"),
    Facebook: require("../assets/images/Social/Facebook.png"),
    Loading: require("../assets/images/98288-loading.json"),
    Loading_1: require("../assets/images/97930-loading.json"),
    Burger: require("../assets/images/burger.png"),
    Dessert: require("../assets/images/dessert.png"),
    Drinks: require("../assets/images/drinks.png"),
    Noodles: require("../assets/images/noodles.png"),
    Pizza: require("../assets/images/pizza.png"),
    Fried_chicken: require("../assets/images/fried_chicken.png"),
    Delivery_charge: require("../assets/images/delivery_charge.png"),
    Delivery_time: require("../assets/images/delivery_time.png"),
    Marker: require("../assets/images/marker.png"),
}